### ISSUE TITLE
autoload.ini requires "changelanguage", but is not installed via composer.json

### ISSUE THREAD

**Issue by KaiserCh** [fritzmg/contao-multidomain-rebuild-index#1]
When installing via Composer, the Changelanguage-Extension isn't required, but it should be, if it is referenced in the autoload.ini.

But: Is it really necessary? Since I didn't want to install Changelanguage, I just removed the "requires"-line from the autoload.ini without any issues.

**Comment by fritzmg** [comment]
Oh, sorry, my mistake. Copy & Paste error ;). Will fix in a minute.

**Comment by fritzmg** [comment]
Fixed in c4c546630fd704e6862af64268b22d06e6216235 (and new release tag created)
